In [1]:
import numpy as np

first_nature_vector = np.arange(1, 11)
print(f"1.Одновимірний масив  з першими 10-ма натуральними:\n{first_nature_vector}")

matrix_zero = np.zeros((3, 3))
print(f"2.Матриця 3х3 заповнена нулями:\n{matrix_zero}")

matrix_5x5 = np.random.randint(1, 11, size=(5, 5))
print(f"3.Матриця 5х5 заповнена випадковими числами від 1 до 10:\n{matrix_5x5}")

array_4x4 = np.random.rand(4, 4)
print(f"4.Матриця розміром 4x4 з випадковими дійсними числами від 0 до 1:{array_4x4}")


vector_1 = np.random.randint(1, 11, size=(5,))
vector_2 = np.random.randint(1, 11, size=(5,))
sum_vectors = vector_1 + vector_2
minus_vectors = vector_1 - vector_2
product_vectors = vector_1 * vector_2
print(
    "5.Сума, різниця, добуток векторів:\n",
    sum_vectors,
    "\n",
    minus_vectors,
    "\n",
    product_vectors,
)

vector_1 = np.random.randint(1, 11, size=(7,))
vector_2 = np.random.randint(1, 11, size=(7,))
scalar_product = np.dot(vector_1, vector_2)
print("6.Скалярний добуток векторів:\n", scalar_product)

matrix_1 = np.random.randint(1, 11, size=(2, 2))
matrix_2 = np.random.randint(1, 11, size=(2, 3))
matrix_product = np.dot(matrix_1, matrix_2)
print("7.Добуток матриць:\n", matrix_product)

base_matrix = np.random.randint(1, 11, size=(3, 3))
inverse_matrix = np.linalg.inv(base_matrix)
print("8.Обернена матриця:\n", inverse_matrix)

base_matrix = np.random.rand(4, 4)
transport_matrix = base_matrix.T
print("9.Транспонована матриця:\n", transport_matrix)

matrix = np.random.randint(1, 11, size=(3, 4))
vector = np.random.randint(1, 11, size=(4,))
result = np.dot(matrix, vector)
print("10.Результат множення матриці на вектор:\n", result)

matrix = np.random.rand(2, 3)
vector = np.random.rand(
    3,
)
result = np.dot(matrix, vector)
print("11.Результат множення матриці на вектор з дійсними числами:\n", result)

matrix_1 = np.random.randint(1, 11, size=(3, 3))
matrix_2 = np.random.randint(1, 11, size=(3, 3))
result = matrix_1 * matrix_2
print("12.Результат  поелементного  множення матриць:\n", result)

matrix_1 = np.random.randint(1, 11, size=(3, 3))
matrix_2 = np.random.randint(1, 11, size=(3, 3))
result = np.dot(matrix_1, matrix_2)
print("13.Добуток матриць:\n", result)

matrix = np.random.randint(1, 101, size=(5, 5))
result = np.sum(matrix)
print("14.Сума елементів матриці:\n", result)

matrix_1 = np.random.randint(1, 11, size=(4, 4))
matrix_2 = np.random.randint(1, 11, size=(4, 4))
result = matrix_1 - matrix_2
print("15.Різниця матриць:\n", result)

matrix = np.random.rand(3, 3)

row_sums = np.sum(matrix, axis=1)
vector_column = row_sums.reshape(-1, 1)
print("16.Сума елементів  кожного рядкаматриці:\n", vector_column)

base_matrix = np.random.randint(1, 20, size=(3, 4))
squared_matrix = np.power(base_matrix, 2)
print("17.Квадрат матриці:\n", squared_matrix)

base_vector = np.random.randint(1, 50, size=(4,))
new_vector = np.power(base_vector, 0.5)
print("18.Вектор з квадратними коренями:\n", new_vector)


1.Одновимірний масив  з першими 10-ма натуральними:
[ 1  2  3  4  5  6  7  8  9 10]
2.Матриця 3х3 заповнена нулями:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
3.Матриця 5х5 заповнена випадковими числами від 1 до 10:
[[ 7 10  8  8  2]
 [ 7  4  1  3  5]
 [ 5  2  6  2  4]
 [10 10  7  2  1]
 [10  9  8  7  5]]
4.Матриця розміром 4x4 з випадковими дійсними числами від 0 до 1:[[0.4976552  0.42036623 0.10891519 0.8308299 ]
 [0.54318438 0.84951544 0.51444838 0.45902791]
 [0.42057303 0.52310353 0.38576129 0.54681884]
 [0.88212559 0.98638852 0.62151505 0.44767908]]
5.Сума, різниця, добуток векторів:
 [18 10 12 12  9] 
 [ 0  2  6 -2  7] 
 [81 24 27 35  8]
6.Скалярний добуток векторів:
 205
7.Добуток матриць:
 [[39 50 64]
 [47 52 66]]
8.Обернена матриця:
 [[ 0.16459627  0.02795031 -0.18012422]
 [-0.01552795 -0.04037267  0.14906832]
 [-0.17701863  0.13975155  0.09937888]]
9.Транспонована матриця:
 [[0.84448825 0.23368358 0.5132694  0.95734283]
 [0.71378467 0.95865382 0.10850774 0.45328533]
 [0.93462087 0.